apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/argocd`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: {{ .Values.argocd.namespace }}
          port: 80
          scheme: http
      # 'priority' must > traefik-dashboard priority(46) to avoid 404 /api/v1/settings
{{/*      priority: 100*/}}
{{/*      middlewares:*/}}
{{/*        - name: argocd-stripprefix*/}}
{{/*        - name: argocd-headers*/}}
  tls: {}
{{/*---*/}}
{{/*apiVersion: traefik.io/v1alpha1*/}}
{{/*kind: Middleware*/}}
{{/*metadata:*/}}
{{/*  name: argocd-stripprefix*/}}
{{/*  namespace: argocd*/}}
{{/*spec:*/}}
{{/*  stripPrefix:*/}}
{{/*    prefixes:*/}}
{{/*      - /argocd*/}}
{{/*---*/}}
{{/*apiVersion: traefik.io/v1alpha1*/}}
{{/*kind: Middleware*/}}
{{/*metadata:*/}}
{{/*  name: argocd-headers*/}}
{{/*  namespace: argocd*/}}
{{/*spec:*/}}
{{/*  headers:*/}}
{{/*    customRequestHeaders:*/}}
{{/*      X-Forwarded-Prefix: "/argocd"*/}}